### ISSUE TITLE
Find-UnitySetupInstaller reports an error searching for 2019.1.0b9

### ISSUE THREAD

**Issue by jwittner** [Microsoft/unitysetup.powershell#165]
```
PS> Find-UnitySetupInstaller -Version 2019.1.0b9 2>&1 > error.txt
Could not find archives for Unity version 2019.1.0b9
At C:\Users\jowitt\Documents\WindowsPowerShell\Modules\unitysetup\5.1.111\UnitySetup.psm1:397 char:13
+             throw "Could not find archives for Unity version $Version ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...sion 2019.1.0b9:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find archives for Unity version 2019.1.0b9
```
[error.txt](https://github.com/Microsoft/unitysetup.powershell/files/3031784/error.txt)

**Comment by FejZa** [comment]
I noticed this as well. I think it's because the url for the component installers is different for betas. E.g.:

https://beta.unity3d.com/download/f1481f10a935/Windows64EditorInstaller/UnitySetup64.exe

compared to

https://download.unity3d.com/download_unity/5063218e4ab8/Windows64EditorInstaller/UnitySetup64.exe

**Comment by StephenHodgson** [comment]
I wonder if that was a recent change
